[installer, ws-manager]: Use installation shortname in URL templates
gitpod-io/gitpod pull request #10152
Opened 2022-05-20 12:39 UTC by andrew-farries

## Description

ℹ️ ℹ️ ℹ️ ℹ️ 

This is a second attempt at #10127, which was reverted (#10143) as it broke preview environments. See [this comment](https://github.com/gitpod-io/gitpod/issues/9875#issuecomment-1132803114) in #9875. The last commit on the branch is a workaround for the preview environment issue.

 ℹ️ ℹ️ ℹ️ ℹ️ 

As described in https://github.com/gitpod-io/gitpod/issues/9875, failing image builds currently fail to produce any useful output. A possible cause, as described in [this comment](https://github.com/gitpod-io/gitpod/issues/9875#issuecomment-1129924819), is that the format of the `ws-manager` `WorkspaceURLTemplate` strings is wrong. 

When we deployed with the old helm chart, these values were set in the relevant configmap like this:

https://github.com/gitpod-io/gitpod/blob/2f988c93499926bd34d6728defbd9d9c0964797e/chart/templates/ws-manager-configmap.yaml#L74-L75

ie, they included a suffix after the `ws`. 

This PR tailors the installer output to produce these URLs in the same way the old helm chart did. Installation short name suffixes like `eu-02` are set here:

https://github.com/gitpod-io/ops/blob/main/deploy/production/meta-eu02/app/installer-config.yaml#L6

so the URLs will now look like `https://{{ .Prefix }}.ws-eu02.example.com`.

## Related Issue(s)
Fixes https://github.com/gitpod-io/gitpod/issues/9875

## How to test

I've tested this change in staging by editing the `ws-manager` configmap in staging to contain the correct URLs, restarting `ws-manager` and running an image build. I was able to see image build logs as expected:

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/8225907/169295310-9c430081-f4d6-4560-bc7c-f00314abf966.png">

## Release Notes
```release-note
[installer] Use installation shortname when constructing ws-manager URL templates
```

## Documentation
None

2022-05-20 12:40 UTC, andrew-farries commented
/hold

2022-05-20 18:01 UTC, sagor999 commented
@meysholdt how do you deploy gitpod in preview env? 
Andrew placed a workaround to make sure this change doesn't break preview, but I feel like we should instead fix the way we are deploying in preview (remove `default` as shortname)

2022-05-23 22:57 UTC, sagor999 commented
@gitpod-io/platform for comment above. can you provide insight before we will merge this.

2022-05-24 07:30 UTC, mads-hartmann commented
@andrew-farries @sagor999 The Werft job uses the Gitpod Installer to generate a config for the installer and then modifies it quite heavily for preview environments. The implementation is [here](https://github.com/gitpod-io/gitpod/blob/main/.werft/jobs/build/installer/installer.ts).

The metadata.shortname is set to `default` by the installer when generating the config. I verified by running the Installer from my workspace off main.

```
gitpod /workspace/gitpod/install/installer (main) $ go run main.go  init | grep -6 metadata
  inCluster: true
database:
  inCluster: true
disableDefinitelyGp: true
domain: ""
kind: Full
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
observability:
  logLevel: info
```

So the change you want to make (if you just want to remove `metadata.shortname` from the config used for preview environments) is something like this

```diff
diff --git a/.werft/jobs/build/installer/installer.ts b/.werft/jobs/build/installer/installer.ts
index 52edde6f6..ea2a83671 100644
--- a/.werft/jobs/build/installer/installer.ts
+++ b/.werft/jobs/build/installer/installer.ts
@@ -58,6 +58,7 @@ export class Installer {
         this.options.werft.log(slice, "Adding extra configuration");
         try {
             this.getDevCustomValues(slice)
+            this.configureMetadata(slice)
             this.configureContainerRegistry(slice)
             this.configureDomain(slice)
             this.configureWorkspaces(slice)
@@ -92,6 +93,10 @@ export class Installer {
         exec(`yq m -i ${this.options.installerConfigPath} ${WORKSPACE_SIZE_CONFIG_PATH}`, { slice: slice });
     }
 
+    private configureMetadata(slice: string): void {
+        exec(`yq d -i ${this.options.installerConfigPath} metadata.shortname `, { slice: slice });
+    }
+
     private configureContainerRegistry(slice: string): void {
         exec(`yq w -i ${this.options.installerConfigPath} certificate.name ${this.options.proxySecretName}`, { slice: slice });
         exec(`yq w -i ${this.options.installerConfigPath} containerRegistry.inCluster false`, { slice: slice });
```

2022-05-24 13:16 UTC, andrew-farries commented
I've removed the `installation.shortname` when deploying to a preview environment. Previews still appear to work.

2022-05-24 18:09 UTC, sagor999 commented
/werft run with-clean-slate-deployment=true

2022-05-24 18:24 UTC, sagor999 commented
@andrew-farries can you rebase your PR? There is a breaking change without which build fails now :(

2022-05-25 08:57 UTC, andrew-farries commented
/werft run with-clean-slate-deployment=true

2022-05-25 09:17 UTC, corneliusludmann approved these changes

2022-05-25 09:45 UTC, andrew-farries commented
Tests failing due to this: https://github.com/gitpod-io/gitpod/pull/10243. 

Will rebase again when that's resolved.

2022-05-25 09:52 UTC, kylos101 commented
@sagor999 could you test the installer asset produced by this build in an ephemeral cluster? I'm worried this could impact our post processing for `ws-proxy`.

2022-05-25 09:54 UTC, kylos101 commented
> @sagor999 could you test the installer asset produced by this build in an ephemeral cluster? I'm worried this could impact our post processing for `ws-proxy`.

@Furisto wanted to give you a heads up on this, as it could impact our ability to deploy workspace clusters.

2022-05-25 17:53 UTC, sagor999 commented
@kylos101 tested ephemeral cluster creation using installer from this branch. All worked fine. Was able to start workspace in that cluster.

2022-05-25 17:56 UTC, sagor999 approved these changes

2022-05-27 12:23 UTC, geropl commented on install/installer/pkg/components/ws-manager/configmap_test.go
> +			ExpectedWorkspacePortURLTemplate: "https://{{ .WorkspacePort }}-{{ .Prefix }}.ws-eu02.example.com",
:+1:

2022-05-27 12:23 UTC, geropl commented on install/installer/pkg/components/ws-manager/configmap_test.go
> +			ExpectedWorkspacePortURLTemplate: "https://{{ .WorkspacePort }}-{{ .Prefix }}.ws.example.com",
:+1:

2022-05-27 12:40 UTC, geropl commented
> I'm more concerned about the consequences of removing the installation shortname rather than the mechanics of how to do it, given the comment here from @geropl:

@andrew-farries I added that line when making `installationShortname` editable (again) and kept the "default" instead of moving to "" (empty string), because I did not want to run into migration trouble with existing self-hosted installations.

The problem is that whatever we put into `installationShortname` is what new workspaceInstances get set as "region". And for the lifetime of a workspace, we need to make sure there is a ws-manager registered for exactly that "region"/"cluster".

> But I guess we can leave it as the default in the installer and remove it specifically for preview environments.

:100: This is what I would have done as well.

2022-05-27 12:41 UTC, geropl commented on install/installer/pkg/components/ws-manager/configmap.go
> +	if ctx.Config.Metadata.InstallationShortname != "" {
@andrew-farries IMO we need to check for `!= "" && != "default", no? (cmp test cases below)

2022-05-27 12:42 UTC, geropl commented on install/installer/pkg/components/ws-manager/configmap_test.go
> +			ExpectedWorkspacePortURLTemplate: "https://{{ .WorkspacePort }}-{{ .Prefix }}.ws.example.com",
@andrew-farries We need a test case "with 'default' as installation shortname" to cover all existing self-hosted installations out there I think. That will lead us to [the comment above](https://github.com/gitpod-io/gitpod/pull/10152/files#r883577546) I think.

2022-05-27 12:42 UTC, geropl requested changes
https://github.com/gitpod-io/gitpod/pull/10152/files#r883578267

2022-05-27 14:35 UTC, geropl approved these changes
Fixes (my own) complaint with [this commit](https://github.com/gitpod-io/gitpod/pull/10152/commits/88230166a9495202802e844cd98fd4dcf9dde61f).

2022-05-27 14:37 UTC, merged