Add S3 bucket name to kots config
gitpod-io/gitpod pull request #10188
Opened 2022-05-23 14:57 UTC by nandajavarma

## Description

As a follow up to #10073 , this PR adds the bucket name option to the KOTS config. This PR depends on the following PRs for proper working:
- #10073 
- #10083 
- #9942 

The resulting UI would have the following content:

![s3-bucket](https://user-images.githubusercontent.com/2624550/169846423-87530c7c-71ba-41da-b95b-bdb10d5525ed.png)

## Related Issue(s)

Fixes #10100

## How to test

Setting up replicated with the changes from this PR and the above mentioned PRs will give the option to provide bucket name.

## Release Notes

```release-note
[kots] Add `S3 bucket name` option to KOTS config  
```

## Documentation

2022-05-23 14:58 UTC, nandajavarma commented
/hold This PR depends on the following PRs for proper working:
- https://github.com/gitpod-io/gitpod/pull/10073
- https://github.com/gitpod-io/gitpod/pull/10083
- https://github.com/gitpod-io/gitpod/pull/9942

2022-05-23 15:07 UTC, corneliusludmann approved these changes
:rocket:

2022-05-23 23:24 UTC, sagor999 commented
![image](https://user-images.githubusercontent.com/18602811/169919864-945c3977-5b98-49dd-9235-ce76c877ec88.png)
I would suggest updating this section to something like this:
`Name of S3 bucket to be used as storage. If left empty, Gitpod will create bucket per each user. If set, then all data will be stored inside one bucket.`

2022-05-23 23:27 UTC, sagor999 requested changes

2022-05-23 23:27 UTC, sagor999 commented on install/kots/manifests/kots-config.yaml
> +          help_text: Name of the S3 bucket to be used as storage. If left empty, buckets will be created by Gitpod using the provided credentials.
```suggestion
          help_text: Name of S3 bucket to be used as storage. If left empty, Gitpod will create bucket per each user. If set, then all data will be stored inside one bucket.
```

2022-05-25 07:51 UTC, nandajavarma commented
/unhold All the dependencies are merged!

2022-05-25 08:18 UTC, merged