Remove the memory requests for workspaces
gitpod-io/gitpod pull request #10191
Opened 2022-05-23 15:57 UTC by vulkoingim

## Description

Remove the memory requests for workspaces. This should allow for more workspaces to fit in preview env by essentially ensuring that the pods will always get scheduled (unless there's not enough CPU). They would still be killed if the node runs out of memory, though.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/10028

2022-05-23 15:57 UTC, roboquat commented
@vulkoingim: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-05-24 07:05 UTC, mads-hartmann requested changes
A bit of context that I realise might be missing. The Gitpod Installer (the source in `/install/installer`) is used to Install Gitpod in general. We use it in preview environment, but also in SaaS and Self-Hosted. So we have to be careful about making changes to the config, and in this case we just want to change the config of Gitpod in preview environments.

To change resource requests for workspaces in preview environments you'd want to make the change in the Werft job where we're generating (and modifying) the configuration file for the Gitpod Installer, rather in the Gitpod Installer itself.

For workspaces that change would be here

https://github.com/gitpod-io/gitpod/blob/e148325fbca1ae4f3f23f5ccafe388deb8ab5dd0/.werft/jobs/build/installer/installer.ts#L107-L110

2022-05-24 13:38 UTC, vulkoingim commented
/werft run

2022-05-24 14:23 UTC, mads-hartmann approved these changes

2022-05-24 14:24 UTC, merged