[dashboard] remove deprecated tailwind filter
gitpod-io/gitpod pull request #10268
Opened 2022-05-25 23:09 UTC by flaming-codes

## Description
Remove the depreacted **tailwind-filters** package and replace its usage w/ native tailwind utility classes.

## Related Issue(s)
Fixes https://github.com/gitpod-io/gitpod/issues/10004

## How to test
No specific test for these styles are available.

## Release Notes

```release-note
NONE
```

## Documentation

2022-05-25 23:10 UTC, flaming-codes commented on components/dashboard/src/index.css
> -    }
Not required any more, as the setting to enable `dark:invert` is added to the `tailwind.config.js` w/ this PR.

2022-05-26 12:24 UTC, gtsiolis commented
Looking at this now! 👀 

/werft run

2022-05-26 13:36 UTC, gtsiolis requested changes
Thanks for contributing, @flaming-codes! ✨ 

Changes look good! However, the filters from tailwind do not seem to work over SVG images. Wondering if this is a known issue since [`filter`] property is expected to work with SVGs, too. 💭 

| Login  | Login (Repository) | First time log in modal | Preferences |
|-|-|-|-|
| <img width="1440" alt="Screenshot 2022-05-26 at 3 40 47 PM (2)" src="https://user-images.githubusercontent.com/120486/170497479-fccaa607-2756-4f6d-ab73-5fc98c202429.png"> | <img width="1440" alt="Screenshot 2022-05-26 at 3 40 43 PM (2)" src="https://user-images.githubusercontent.com/120486/170497484-f0e74ee2-1d5c-4e7b-a1c0-dbd0531a1828.png">  | <img width="1440" alt="Screenshot 2022-05-26 at 3 41 41 PM (2)" src="https://user-images.githubusercontent.com/120486/170497505-c5e5c307-b95d-4c36-b6fe-f33a0b00ba84.png"> | <img width="1440" alt="Screenshot 2022-05-26 at 3 41 51 PM (2)" src="https://user-images.githubusercontent.com/120486/170497509-ec39abe2-fd36-4d9a-9c79-3deb7dbbaf4b.png"> |

Let me spin up another preview environment instance below.

2022-05-26 13:36 UTC, gtsiolis commented
/werft run

2022-05-26 13:37 UTC, gtsiolis commented
You'll also need to sign a Contributor License Agreement (CLA)[[1](https://en.wikipedia.org/wiki/Contributor_License_Agreement)] once before merging your first contribution. Looping in [@meysholdt](https://github.com/meysholdt) to reach out about the CLA. 🏓

2022-05-26 20:43 UTC, flaming-codes commented
Added missing utility class, as required by Tailwind 2.x. Whenever we upgrade to 3.x, the `filter`-utility can be removed.

| Login | Providers |
| --- | --- |
| ![Screenshot 2022-05-26 at 22 37 16](https://user-images.githubusercontent.com/11635736/170576631-8176eb39-bcb5-47b9-8cd6-73107bf1c1ba.png) | ![Screenshot 2022-05-26 at 22 36 46](https://user-images.githubusercontent.com/11635736/170576675-a7a83f22-511a-4006-b1b4-4f8d13632e00.png) |

2022-05-27 09:44 UTC, gtsiolis commented
/werft run

2022-05-27 20:14 UTC, flaming-codes commented
/werft run

2022-05-30 11:38 UTC, gtsiolis commented
/werft run

2022-05-30 15:13 UTC, gtsiolis commented
/werft run

2022-05-30 17:24 UTC, gtsiolis commented
/werft run

2022-06-01 18:30 UTC, flaming-codes commented
@meysholdt I would really like to sign the CLA so that I can continue contributing to Gitpod. My email is tom@flaming.codes. Thanks!

2022-06-10 11:04 UTC, aboqasem commented
Hi @flaming-codes, [here are the instructions on signing the CLA](https://github.com/gitpod-io/gitpod/blob/main/dev/addlicense/CONTRIBUTING.md).

2022-06-14 15:08 UTC, flaming-codes commented
> Hi @flaming-codes, [here are the instructions on signing the CLA](https://github.com/gitpod-io/gitpod/blob/main/dev/addlicense/CONTRIBUTING.md).

I already signed the CLA, is there anything more to do? Thanks!

2022-07-11 08:54 UTC, flaming-codes commented
@gtsiolis What's the status on this from your side? I signed the CLA a long time ago, is there anything to do on my part? Thanks!

2022-07-11 13:16 UTC, gtsiolis commented
@flaming-codes Did you receive a CLA doc to sign from @meysholdt as described in https://github.com/gitpod-io/gitpod/pull/10268#issuecomment-1138589118? I've also asked the team internally to confirm.

2022-07-11 13:20 UTC, flaming-codes commented
> @flaming-codes Did you receive a CLA doc to sign from @meysholdt as described in [#10268 (comment)](https://github.com/gitpod-io/gitpod/pull/10268#issuecomment-1138589118)? I've also asked the team internally to confirm.

Yes, and I signed it some weeks ago.

2022-07-26 10:08 UTC, meysholdt commented
hi @flaming-codes, I checked, but we don't have a signed CLA from your on record. Maybe that is because the link from the comments above points to Googles CLA and not to Gitpods CLA. Apologies for the confustion. Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via moritz@gitpod.io.

2022-07-26 10:11 UTC, flaming-codes commented
> hi @flaming-codes, I checked, but we don't have a signed CLA from your on record. Maybe that is because the link from the comments above points to Googles CLA and not to Gitpods CLA. Apologies for the confustion. Can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [moritz@gitpod.io](mailto:moritz@gitpod.io).

@meysholdt Great, thanks! I signed the doc provided by the link.

2022-07-26 10:15 UTC, meysholdt commented
Awesome, thank you! I've received the signed CLA and filed a PR to remove the misleading instructions: https://github.com/gitpod-io/gitpod/pull/11646

2022-08-01 07:12 UTC, jankeromnes commented
/werft run

2022-08-01 07:29 UTC, jankeromnes commented
/werft run with-preview

2022-08-01 20:00 UTC, flaming-codes commented
Due to the lack of action for a final review and me atm not having the necessary time to further work on it, I'm closing this PR.

2022-08-01 20:00 UTC, closed without merging