Add cache for ide-proxy static file
gitpod-io/gitpod pull request #10493
Opened 2022-06-07 07:08 UTC by iQQBot

## Description

Add cache for ide-proxy static file

## Related Issue(s)

Fixes #

## How to test

Open preview environment, open chrome devtool network, go to preview environment setting -> preference
check devtool, the ide logo should have the header 
```HTTP
Cache-Control: public, max-age=31536000
```

## Release Notes

```release-note
```

## Documentation

2022-06-07 07:08 UTC, roboquat commented
@iQQBot: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-06-07 20:38 UTC, jeanp413 requested changes
For this to properly work we need to add a hash to the static files names, if not the cache will never be invalidated, see https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2

2022-06-08 02:41 UTC, jeanp413 commented
>  if we want to change them, we will change the name (this needs to be done with the ide-server-config update)

Then we need to add a comment in the ide-server-config explaining this so it's not forgotten

2022-06-08 04:32 UTC, jeanp413 commented
Adding a Readme.md file in `components/ide-proxy` with the required steps to update the images would be helpful

2022-06-08 04:42 UTC, jeanp413 approved these changes

2022-06-08 04:43 UTC, merged