[server] don't allow more than three usages
gitpod-io/gitpod pull request #13186
Opened 2022-09-21 18:36 UTC by svenefftinge

## Description
Adds checks for phone numbers being used by abusers or used too often (>3) 

## Related Issue(s)

Fixes #12883

## How to test

## Release Notes

```release-note
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

2022-09-21 18:36 UTC, roboquat commented
@svenefftinge: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-21 21:21 UTC, atduarte reviewed
This is awesome! Thank you, Sven 🙏 

Looking at the code out of curiosity found something you will notice also pretty quickly :) 

PS: Would it make sense and be sensible to also stop overriding the phone number on delete as part of this ([here](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/user/user-deletion-service.ts#L157))? Asking because a potential way for an abuser to avoid both these checks is requesting the account to be deleted.

2022-09-21 21:21 UTC, atduarte commented on components/server/src/auth/verification-service.ts
> +        const isBlockedNumber = this.userDB.countUsagesOfPhoneNumber(phoneNumber);
```suggestion
        const isBlockedNumber = this.userDB.isBlockedPhoneNumber(phoneNumber);
```

2022-09-22 06:34 UTC, easyCZ commented on components/gitpod-db/src/typeorm/migration/1663784254956-IndexPhoneNumber.ts
> +                `ALTER TABLE ${D_B_USER} ADD INDEX (${COL_PHONE_NUMBER}), ALGORITHM=INPLACE, LOCK=NONE `,
What's the expected shape of the phone number here? Is it including spaces? Is it including country codes? Are the country codes encoded as + or 00? Would any of these formats cause issues when checking for the number of times a number has been used?

2022-09-22 06:49 UTC, svenefftinge commented
/werft run

2022-09-22 06:57 UTC, svenefftinge commented on components/gitpod-db/src/typeorm/migration/1663784254956-IndexPhoneNumber.ts
> +                `ALTER TABLE ${D_B_USER} ADD INDEX (${COL_PHONE_NUMBER}), ALGORITHM=INPLACE, LOCK=NONE `,
There are a couple of allowed shapes, which could be exploited to reuse the same number. Is that what you are asking?

2022-09-22 06:58 UTC, easyCZ commented on components/gitpod-db/src/typeorm/migration/1663784254956-IndexPhoneNumber.ts
> +                `ALTER TABLE ${D_B_USER} ADD INDEX (${COL_PHONE_NUMBER}), ALGORITHM=INPLACE, LOCK=NONE `,
Basically. Could we in the least do the following transformations:

2022-09-22 06:59 UTC, svenefftinge commented on components/gitpod-db/src/typeorm/migration/1663784254956-IndexPhoneNumber.ts
> +                `ALTER TABLE ${D_B_USER} ADD INDEX (${COL_PHONE_NUMBER}), ALGORITHM=INPLACE, LOCK=NONE `,
We could store the number in https://en.wikipedia.org/wiki/E.164. I'll check later if that's easy enough.

2022-09-22 07:02 UTC, svenefftinge commented
/hold

2022-09-22 07:12 UTC, easyCZ requested changes
Requesting changes as per [internal thread](https://gitpod.slack.com/archives/C01MLB7J24T/p1663830093846229)

2022-09-23 12:19 UTC, easyCZ approved these changes
LGTM, one comment about correctly distinguishing user errors and server errors.

/hold

2022-09-23 12:19 UTC, easyCZ commented on components/server/src/auth/verification-service.ts
> +            throw new Error("The given phone number is blocked due to abuse.");
Can we throw this as a user error here? Otherwise it will count towards server errors in our metrics.

2022-09-23 12:19 UTC, easyCZ commented on components/server/src/user/phone-numbers.ts
> +export function formatPhoneNumber(phoneNumber: string): string {
👍

2022-09-23 13:26 UTC, svenefftinge commented
/unblock

2022-09-23 13:27 UTC, merged