Configure default usage limits for new Stripe customers
gitpod-io/gitpod pull request #13535
Opened 2022-10-03 14:05 UTC by jankeromnes

## Description

Configure default usage limits for new Stripe customers, but don't use them anywhere yet (precursor to https://github.com/gitpod-io/gitpod/pull/13398)

## Related Issue(s)

Part of https://github.com/gitpod-io/gitpod/issues/13389

## How to test

1. Should build

## Release Notes

```release-note
NONE
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

2022-10-03 14:25 UTC, jankeromnes commented
/werft run

2022-10-03 15:29 UTC, easyCZ commented on components/usage/pkg/server/server.go
> +	DefaultSpendingLimit db.DefaultUsageLimits `json:"defaultSpendingLimit"`
JSON property still says `spendingLimit`

2022-10-03 15:33 UTC, easyCZ requested changes
Please address commented out test

2022-10-03 15:33 UTC, easyCZ commented on components/usage/pkg/stripe/stripe_test.go
> +		// },
Let's not do this. If this is broken, let's pair and fix it but commenting out tests is only gonna get us to a darker place.

2022-10-03 15:33 UTC, easyCZ commented on install/installer/pkg/components/usage/configmap.go
> +			ForStripeUsers: 1000,
This would render these into self-hosted installs by default? Are we happy with that?

2022-10-03 15:33 UTC, easyCZ commented on install/installer/pkg/config/v1/experimental/experimental.go
> +	DefaultSpendingLimit             *db.DefaultUsageLimits `json:"defaultSpendingLimit"`
json property still has `spendingLimit`

2022-10-03 15:33 UTC, easyCZ commented on components/usage/pkg/db/cost_center.go
> +	ForStripeUsers int32 `json:"forStripeUsers"`
What's the difference between Stripe and nonStripe users?

Would it make sense to introduce a child struct which holds the values for User/Teams like this?
```
type Limit struct {
  Team int32
  User int32
}

and use it as 

type DefaultUsageLimits {
  WithoutSubscription Limit
  WithSubscription Limit
}
```

2022-10-04 06:44 UTC, jankeromnes commented
Thanks for the good feedback! But I think I'll stop working on CostCenters for now, and instead focus on the Billing UI improvements.

2022-10-04 06:44 UTC, closed without merging