[usage] Only show team owners
gitpod-io/gitpod pull request #13585
Opened 2022-10-04 14:47 UTC by laushinka

## Description

## Related Issue(s)

Fixes #

## How to test

## Release Notes

```release-note
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [x] /werft with-payment
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

2022-10-04 14:47 UTC, roboquat commented
@laushinka: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-05 05:52 UTC, andrew-farries requested changes

2022-10-05 05:52 UTC, andrew-farries commented on components/server/ee/src/workspace/gitpod-server-impl.ts
>                  let teamOrUser;
This can be made `const` and moved into the switch case on line 2270 where it is used.

2022-10-05 08:43 UTC, easyCZ approved these changes
LGTM, will likely need to squash commits as the last one is just `r`

/hold for squash

2022-10-05 09:52 UTC, laushinka commented
/werft run

2022-10-05 10:12 UTC, laushinka commented
@andrew-farries I think it's not being merged because you have to approve as the change requester 🤔

2022-10-05 10:18 UTC, andrew-farries approved these changes

2022-10-05 10:19 UTC, merged

2022-10-05 10:19 UTC, laushinka commented
Thanks! A bit annoying that it requires that. I wonder if that's something we can change.

2022-10-05 10:29 UTC, andrew-farries commented
I think for a smoother workflow it's often best to approve with a '/hold' rather than requesting changes, then the PR author can make the change and merge without waiting for re-review.

I probably should have done that here.