Fix workspace alerts path
gitpod-io/gitpod pull request #14512
Opened 2022-11-08 11:45 UTC by ArthurSens

## Description

In https://github.com/gitpod-io/gitpod/pull/13850, we split workspace alerts into 2 different folders but forgot to update their paths in the configuration used for previews.

This PR fixes the import pathes.

## Related Issue(s)

Fixes #

## How to test

## Release Notes

```release-note
NONE
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`

2022-11-08 13:30 UTC, kylos101 requested changes
A couple path corrections as per folder structure here: https://github.com/gitpod-io/gitpod/tree/as/fix-preview-alert-path/operations/observability/mixins/workspace/rules

2022-11-08 13:30 UTC, kylos101 commented on .werft/observability/manifests/monitoring-satellite.yaml
> +      path: operations/observability/mixins/workspace/central/rules
```suggestion
      path: operations/observability/mixins/workspace/rules/central
```

2022-11-08 13:30 UTC, kylos101 commented on .werft/observability/manifests/monitoring-satellite.yaml
> +      path: operations/observability/mixins/workspace/satellite/rules
```suggestion
      path: operations/observability/mixins/workspace/rules/satellite
```

2022-11-08 14:23 UTC, ArthurSens commented on .werft/observability/manifests/monitoring-satellite.yaml
> +      path: operations/observability/mixins/workspace/central/rules
Ohm nice catch 😅

2022-11-09 18:08 UTC, kylos101 approved these changes
Good to me!

Over to you @gitpod-io/engineering-delivery-operations-experience !

2022-11-10 05:39 UTC, Pothulapati approved these changes
Paths look correct! :shipit:

2022-11-10 08:26 UTC, merged