Optionally consume Leeway from git
gitpod-io/gitpod pull request #14567
Opened 2022-11-09 16:41 UTC by meysholdt

## Description
Optionally install leeway from git. This is helpful to test new versions of leeway before releasing them.

## Related Issue(s)
Fixes #

## How to test
`werft run github -a leeway-from-git=true` from CI to bypass job protection.

## Release Notes

```release-note
NONE
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

2022-11-10 09:22 UTC, mads-hartmann requested changes
We can't merge this until we cut a new release of Leeway and bump that everywhere. There are quite a few changes on Leeway main that isn't included in v0.3.1 and some of them are breaking, like the removal of --dont-retag

2022-11-11 19:40 UTC, aledbf commented
/approve

2022-11-11 20:10 UTC, aledbf commented
Here is the change that updates leeway in the dev-environment image https://github.com/gitpod-io/gitpod/pull/14631

2022-11-14 15:36 UTC, vulkoingim commented on .werft/build.yaml
> +        scripts/install-leeway-from-git.sh "{{ .Annotations.leewayfromgit }}" | werft log slice "Building fresh Leeway binary from source"
```suggestion
        GOBIN=$(dirname $(which leeway)) go install github.com/gitpod-io/leeway@latest | werft log slice "Building fresh Leeway binary from source"
```

2022-11-14 15:37 UTC, vulkoingim commented on .werft/build.yaml
> +        scripts/install-leeway-from-git.sh "{{ .Annotations.leewayfromgit }}" | werft log slice "Building fresh Leeway binary from source"
Or pass whatever tag to `@latest`

2022-11-14 15:46 UTC, vulkoingim commented on .werft/build.yaml
> +        scripts/install-leeway-from-git.sh "{{ .Annotations.leewayfromgit }}" | werft log slice "Building fresh Leeway binary from source"
Hm you might need go in sudo path, if leeway is in a restricted path. So this should work:

```bash
GOBIN=$(pwd) go install github.com/gitpod-io/leeway@latest && sudo mv leeway $(dirname $(which leeway))
```

2022-11-14 16:06 UTC, meysholdt commented
> We can't merge this until we cut a new release of Leeway and bump that everywhere. There are quite a few changes on Leeway main that isn't included in v0.3.1 and some of them are breaking, like the removal of --dont-retag

Sice Leeway has been released & deployed [here](https://github.com/gitpod-io/gitpod/pull/14567#issuecomment-1312155160), I assume this PR can be merged now.

2022-11-14 16:07 UTC, vulkoingim approved these changes

2022-11-16 10:08 UTC, mads-hartmann approved these changes

2022-11-16 10:09 UTC, merged