Implemented the date feature
gitpod-io/gitpod pull request #16474
Opened 2023-02-20 09:13 UTC by bonysureliya

from date = previous month date
to date = current date
issue:15544

2023-02-20 09:13 UTC, roboquat commented
@bonysureliya: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-02-20 11:17 UTC, gtsiolis commented
/werft run with-preview=true

2023-02-20 11:51 UTC, gtsiolis commented
/werft run with-clean-slate-deployment=true with-preview=true recreate-vm=true

2023-02-20 12:13 UTC, gtsiolis requested changes
Thanks for contributing, @bonysureliya! 🍊 

I couldn't test this in the preview environment as the build was failing[[1](https://werft.gitpod-dev.com/job/gitpod-build-patch-1-fork.12)]:

```
Failed to compile.

src/components/UsageView.tsx
Syntax error: 'finally' expected (57:8)
```

1.  Could you fix this—I'll retrigger the build once you push some changes.
2. You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt

2023-03-03 16:00 UTC, gtsiolis commented
@bonysureliya Friendly reminder from https://github.com/gitpod-io/gitpod/pull/16474#pullrequestreview-1305666955:

> You'll also need to sign a CLA[[1](https://powerforms.docusign.net/30e1aa46-cce5-4bc6-a933-ad02cd8d5ada?env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&accountId=86335c2c-01b9-4edc-a187-014f5150a112)] once before merging your first contribution. Cc @meysholdt

2023-03-06 13:22 UTC, meysholdt commented
Thank you, @bonysureliya, for signing our CLA!

2023-03-09 16:25 UTC, gtsiolis commented
/werft run with-preview

2023-03-10 11:37 UTC, gtsiolis commented
@bonysureliya The usage page still defaults to **Month 1st - Today**.

You can check the preview environment below:

> https://patch-1.preview.gitpod-dev.com/workspaces

2023-03-10 12:16 UTC, gtsiolis reviewed
@bonysureliya I've added one comment above. This seems to behave similarly as the current state, ses https://github.com/gitpod-io/gitpod/pull/16474#issuecomment-1463679242.

2023-03-27 08:04 UTC, easyCZ requested changes

2023-03-27 08:04 UTC, easyCZ commented on components/dashboard/src/components/UsageView.tsx
> +                const prevMonthStr = prevMonth.toISOString().slice(0, 10);
If I'm reading this correctly, this change would ignore the the URL hash parameter and would always set it to one month back. That's actually not the desired behaviour, as it prevents deep-linking of the current view in the URL.

Showing the last 1 month, could be the default behaviour when no hash is supplied, however, but the change as it stands does not do that. You likely want to move the handling into the `!match` case of this if.

2023-03-27 08:56 UTC, bonysureliya reviewed
Review of Date Changing Functionality , @easyCZ  Helped where it was catching bug

2023-04-11 08:10 UTC, gtsiolis commented
@bonysureliya Is this ready for another review? I'd love to get this merged and fix this annoying issue in https://github.com/gitpod-io/gitpod/pull/16474.

Could you also make sure this is up-to-date with the `main` branch?

Cc @easyCZ

2023-04-20 04:06 UTC, bonysureliya commented
Yes I will be completing the issue in one or two days.

2023-05-08 23:46 UTC, closed without merging