trrr
gitpod-io/gitpod pull request #19326
Opened 2024-01-15 19:30 UTC by filiptronicek

## Description

## Related Issue(s)

Fixes #

## How to test

## Documentation

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [x] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

2024-01-18 19:09 UTC, filiptronicek commented
/gh run recreate-vm=true

2024-01-22 18:15 UTC, filiptronicek commented
/gh run recreate-vm=true

2024-01-23 08:06 UTC, Siddhant-K-code commented on components/gitpod-db/src/typeorm/workspace-db-impl.ts
> +    async findPrebuiltWorkspacesByOrganization(
Suggestion (non-blocking): We can wrap the whole logic of this in a `try-catch` block:

```ts
    try {
        const repo = await this.getPrebuiltWorkspaceRepo();
        // existing query construction logic
        return await query.getMany();
    } catch (error) {
        // Handle or log the error appropriately
        console.error('Error fetching prebuilt workspaces:', error);
        throw error; 
    }
```

2024-01-23 08:12 UTC, mustard-mh requested changes
We update `useLatestProjectPrebuildQuery` to use new API and use it in `ProjectListItem.tsx` which is accessible in /project route. So once gRPC `prebuild` service is not enabled, it will respond empty.

To fix it:
- Add another useQuery to avoid affect other page
- [nit] if method is not implemented, throw NotImplemented https://github.com/gitpod-io/gitpod/blob/36f02c6fd5382ce31f8c797b99adf10de63edb28/components/dashboard/src/service/json-rpc-prebuild-client.ts#L151

|prebuild off| on|
|:-:|:-:|
|<img width="1457" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/0443d59a-065b-4251-a15f-f51eaa5fecf3">|<img width="1341" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/40569947-66f6-4a37-be17-135262097705">|

2024-01-23 08:12 UTC, mustard-mh requested changes
update: I don't know why it comment twice, keep them just to avoid delete will affect other comments, remove content below

2024-01-23 08:33 UTC, filiptronicek commented on components/server/src/api/prebuild-service-api.ts
> +        if (limit <= 0) {
I think we can align the configurations API. We have a valid use-case for requesting just one prebuild result 👍

2024-01-23 08:40 UTC, mustard-mh commented on components/dashboard/src/data/prebuilds/latest-project-prebuild-query.ts
>  export const useLatestProjectPrebuildQuery = ({ projectId }: Args) => {
Share comment here because direct comment can't be resolved ()
https://github.com/gitpod-io/gitpod/pull/19326/#pullrequestreview-1837977751

2024-01-23 18:00 UTC, filiptronicek commented
@mustard-mh thanks for catching the giant mistake of migrating things when we don't have the method in jrpc! I will revert those now and will add manual testing steps.

2024-01-24 08:23 UTC, mustard-mh approved these changes
LGTM 🎉

2024-01-24 09:59 UTC, merged