[dashboard] Fix GitHub app integration URL in user settings
gitpod-io/gitpod pull request #19329
Opened 2024-01-16 17:07 UTC by Siddhant-K-code

## Description

Bug got introduced in #19057 (cc: @AlexTugarev), which confuses the `appRedirectUrl` with GitHub App settings url (which is a constant URL for every user with GitHub App Id). See linked linear issue for more details.

## Related Issue(s)

Fixes EXP-1152

## How to test

- Open preview environment & complete setup w/ GitHub as Git provider.
- Go to user integrations settings (`/user/integrations`) and click on three dots in `GitHub` item list.
- Click on <kbd>Manage on github.com</kbd> & see fixed URL.

## Documentation

#### Preview status

gitpod:summary

## Build Options

<details>
<summary>Build</summary>

- [ ] /werft with-werft
      Run the build with werft instead of GHA
- [ ] leeway-no-cache
- [ ] /werft no-test
      Run Leeway with `--dont-test`
</details>

<details>
<summary>Publish</summary>

- [ ] /werft publish-to-npm
- [ ] /werft publish-to-jb-marketplace
</details>

<details>
<summary>Installer</summary>

- [ ] analytics=segment
- [ ] with-dedicated-emulation
- [ ] workspace-feature-flags
  Add desired feature flags to the end of the line above, space separated
</details>

<details>
<summary>Preview Environment / Integration Tests</summary>

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [x] /werft with-gce-vm
      If enabled this will create the environment on GCE infra
- [x] /werft preemptible
      Saves cost. Untick this only if you're really sure you need a non-preemtible machine.
- [ ] with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` will be enabled.
- [ ] with-monitoring
</details>

/hold

2024-01-16 19:36 UTC, AlexTugarev requested changes
Hi @Siddhant-K-code! 
Thanks for spotting this. 
Indeed, the path is wrong. It should be `/settings/applications`.
The proposed change doesn't work in Dedicated context, unfortunately.

2024-01-17 03:50 UTC, Siddhant-K-code commented
> Indeed, the path is wrong. It should be /settings/applications.

Did the changes in [`264efb4`](https://github.com/gitpod-io/gitpod/pull/19329/commits/264efb4bf71ea59b8b2c37ceb3d29dda247cc6c9), but this seems confusing (from UX pov) if users have multiple oAuth Apps installed.

<img width="1047" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/312b6f02-b08f-41f2-bc13-c7362d84e2f6">

---


> The proposed change doesn't work in Dedicated context, unfortunately.

I think, this won't be true for all other users in Gitpod Cloud & Dedicated because (assuming) they would be using Gitpod GitHub OAuth App. I think, this would be true in our internal use case to use a custom GitHub App for dedicated.

2024-01-17 07:18 UTC, svenefftinge approved these changes

2024-01-17 07:21 UTC, Siddhant-K-code commented
/unhold

2024-01-17 07:24 UTC, merged