[server] github: allow branch names with special characters
gitpod-io/gitpod pull request #2638
Opened 2020-12-30 20:10 UTC by koushik-ms

Decode branch or commit hash segments with decodeURIComponent to revert
URL encoded strings (e.g., %23 -> #)

Fixes #2624.

2020-12-30 21:19 UTC, koushik-ms commented
Unfortunately, my attempt at adding a test was unsuccessful so far. [This](https://github.com/gitpod-io/gitpod/commit/58856024d04c4589a2f50eee040a44bf02e91891) is the work-in-progress test. However running the tests in that file requires a github api token that apparently belongs to a specific test-user. A github API token with repo scope generated on my user id, for example, wasn't successful in running the tests. I tried, of course, from within a gitpod workspace.

I also think this test-case should be running on a branch in gitpod-test-repo so once I figure out the auth I intend to first raise a PR with test data for that repo. 

Any help on the auth issue would be great. Below is the error message:
```
gitpod /workspace/gitpod/components/server $ yarn run mocha --opts mocha.opts src/github/github-context-parser.spec.ts 
yarn run v1.22.10
$ /workspace/gitpod/node_modules/.bin/mocha --opts mocha.opts src/github/github-context-parser.spec.ts
...
  1 passing (131ms)
  24 failing

  1) TestGithubContextParser
       testErrorContext_01:

      AssertionError: expected { Object (host, scopes, ...) } to deeply equal { Object (host, lastUpdate, ...) }
      + expected - actual

       {
         "host": "github.com"
      -  "messageHint": "missing-identity"
      -  "scopes": [
      +  "lastUpdate": [undefined]
      +  "owner": "blo"
...
```

2021-01-04 03:07 UTC, twtwtw-gj commented
Is it true that this test needs my user access token?
It's terrible. The security of my account would be Threatened.
This test isn't stateless.

Do we have any plan?

2021-01-04 06:52 UTC, csweichel commented
/werft run

2021-01-06 09:27 UTC, svenefftinge commented
/werft run

2021-01-08 10:37 UTC, DvalCaruso requested changes
no

2021-01-08 10:38 UTC, DvalCaruso approved these changes

2021-01-08 16:13 UTC, AlexTugarev commented
/werft run

2021-01-08 16:28 UTC, AlexTugarev approved these changes
<img width="769" alt="Screen Shot 2021-01-08 at 17 24 04" src="https://user-images.githubusercontent.com/914497/104039613-e282b480-51d6-11eb-9f01-be828259838c.png">

Just tested it, and it works as advertised!
Thanks @koushik-ms!

2021-01-08 16:38 UTC, AlexTugarev commented
@koushik-ms, and @twtwtw-gj, regarding the context parser tests, yes those tests require a PAT to be injected as env var. This way we can let tests run in `werft` without exposing those tokens. 

Unfortunately, we haven't yet set up test user accounts, nor migrated the existing tests to run as expected with those test accounts. As of now we keep the tests running in a private `werft` instance, but we definitely should migrate the tests, which would also make contribution of tests (in the test repo) possible as proposed ☝🏻 by @koushik-ms.

2021-01-08 17:23 UTC, merged

2021-01-08 19:26 UTC, koushik-ms commented
Thanks for accepting the PR. I love gitpod and I am really happy this got merged.

2021-01-09 02:08 UTC, twtwtw-gj commented
Thank you.