[code] workspace sharing support
gitpod-io/gitpod pull request #4580
Opened 2021-06-23 07:08 UTC by akosyakov

#### What it does

- fix #2812: workspace sharing support

Change in Gitpod Code: https://github.com/gitpod-io/vscode/commit/e074a595b2901b745df223682ac1a9a2c04f1e35

#### How to test

- Start a workspace.
- You should see `Share` status bar indicator, click on it to start sharing.
- Open a workspace link by another user and check that a workspace can be accessed. Share indicator should show `Joined`, clicking on it should not do anything.
- Go to owner window again, share indicator should show `Shared` now, clicking on it should stop sharing.
- You can also verify that there are `Share` and `Stop Sharing` commands under the main menu and the remote menu (click on remote indicator in the status bar).

2021-06-25 11:57 UTC, JanKoehnlein commented
/werft run

2021-06-25 12:25 UTC, JanKoehnlein commented
/werft run

2021-06-25 12:46 UTC, JanKoehnlein commented
/werft run

2021-06-25 13:08 UTC, JanKoehnlein commented
/werft run with clean-slate-deployment

2021-06-25 13:09 UTC, JanKoehnlein commented
/werft run with-clean-slate-deployment

2021-06-25 13:15 UTC, JanKoehnlein commented
/werft run

2021-06-25 13:22 UTC, JanKoehnlein commented
/werft run

2021-06-25 13:45 UTC, JanKoehnlein commented
/werft run with-clean-slate-deployment

2021-06-25 14:31 UTC, JanKoehnlein requested changes
Didn't work 😔

- The "Joined" indicator didn't appear
- In both workspaces, I could click on "Share" to unshare
- Unsharing had no effect on the current connection (new connections were disabled)

I tried with two different sharing users

2021-06-25 14:32 UTC, JanKoehnlein commented
PS: The preview envs are currently pretty broken. I suggest to always deploy `with-clean-slate-deployment`

2021-06-26 02:45 UTC, akosyakov commented
/werft run

2021-06-26 05:33 UTC, akosyakov commented
@JanKoehnlein thanks for testing! The issue was that even for invited user I would use an owner user in the vscode extension. I changed now that a user is fetched from the browser session to detect whether current window own the workspace or not. I also limited commands which invited user can access. Please see test description above.

2021-06-28 07:07 UTC, akosyakov commented
/werft run

2021-06-28 08:10 UTC, JanKoehnlein approved these changes
LGTM now.

I suppose "unsharing" a workspace doesn't terminate an existing connection, or should it?

2021-06-28 08:14 UTC, akosyakov commented
> I suppose "unsharing" a workspace doesn't terminate an existing connection, or should it?

It is known a bug for long time. We don't have any channel to communicate that a workspace is unshared. Although if you refresh the page then you won't be able to access anymore.

2021-06-28 08:18 UTC, merged

2021-06-28 12:07 UTC, mikenikles commented
This is exciting news! Could you add an item to the `CHANGELOG.md` file please so we won't miss it when we announce the next release 🙏?