[bridge] Set stoppedTime while workspace is stopping
gitpod-io/gitpod pull request #4833
Opened 2021-07-15 11:31 UTC by csweichel

there's no need to include the time our workspaces take to stop into account when computing workspace runtime (which is accounting relevant).

fixes #4818

2021-07-15 11:48 UTC, geropl commented
Code-wise this looks ok.

But to me this feels like accumulating debt: Why not have a 2nd field called `stoppingTime`? :thinking:

2021-07-15 12:11 UTC, csweichel commented
> Code-wise this looks ok.
> 
> But to me this feels like accumulating debt: Why not have a 2nd field called `stoppingTime`? 🤔

done

2021-07-15 15:33 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4833#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **geropl** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @geropl` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)**
- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["geropl"]} -->

2021-07-15 15:34 UTC, csweichel commented
/assign @geropl

2021-07-15 15:50 UTC, csweichel commented
/werft run no-preview

2021-07-19 08:43 UTC, geropl commented
> done

Awesome. Will start review now...

2021-07-19 09:16 UTC, geropl requested changes
Looks good! IMO there two things missing:
 1. selecting `stoppingTime` when selecting sessions from the DB
 1. setting `stoppedTime` in bridge
 
 I made the changes [here](https://github.com/gitpod-io/gitpod/commit/3f1eefc1ee54e580295e419ea927323d041aca06), feel free to cherry-pick.

2021-07-19 09:16 UTC, geropl commented on components/ws-manager-bridge/src/bridge.ts
>                      instance.status.phase = "stopped";
`instance.stoppedTime = new Date().toISOString();` went missing here, should be re-added.

2021-07-19 09:16 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4833#" title="Author self-approved">csweichel</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **geropl** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)**
- **[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)**
- **[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)**
- **[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)**
- **[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["geropl"]} -->

2021-07-20 07:24 UTC, svenefftinge commented on components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
> +    stoppingTime?: string;
a comment that explains what the difference between `stoppingTime` and `stoppedTime` is would help avoid missunderstandings.

2021-07-20 07:39 UTC, csweichel commented
Thank you @geropl - I've cherry-picked your changes.

2021-07-20 09:10 UTC, geropl commented on components/server/src/workspace/workspace-starter.ts
> +            instance.stoppingTime = new Date().toISOString();
Maybe a nit, but: guaranteed `stoppingTime == stoppedTime` is a nice thing to have for downstream usage: analytics, bug hunting, ad-hoc DB fixes, etc.

2021-07-20 09:11 UTC, geropl commented on components/ws-manager-bridge/src/bridge.ts
> +            instance.stoppingTime = new Date().toISOString();
Maybe a nit, but: guaranteed `stoppingTime == stoppedTime` is a nice thing to have for downstream usage: analytics, bug hunting, ad-hoc DB fixes, etc.

2021-07-20 09:15 UTC, geropl commented
I just tested and somehow ended up in a re-start loop :confused: Will investigate.

2021-07-20 09:30 UTC, geropl approved these changes
Works as advertised! Feels wholesome to have that column, finally :-D

Happy to fix the nits separately (if at all).

2021-07-20 09:31 UTC, roboquat commented
LGTM label has been added.  <details>Git tree hash: 564c438d498ff7b96eaa7fceed0323b3463b244f</details>

2021-07-20 09:31 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/4833#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitpod/pull/4833#pullrequestreview-710372785" title="Approved">geropl</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[components/ee/payment-endpoint/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ee/payment-endpoint/OWNERS)~~ [geropl]
- ~~[components/gitpod-db/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/OWNERS)~~ [geropl]
- ~~[components/gitpod-protocol/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/OWNERS)~~ [geropl]
- ~~[components/server/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/server/OWNERS)~~ [geropl]
- ~~[components/ws-manager-bridge/OWNERS](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/OWNERS)~~ [geropl]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-20 09:31 UTC, merged