Added a script to download k3s kubeconfig for preview-environments
gitpod-io/gitpod pull request #7893
Opened 2022-01-28 12:31 UTC by wulfthimm

## Description

This adds the script `install-k3s-environment.sh`. It connects to the k3s cluster inside the preview VM and downloads the kubeconfig `k3s.yaml`  replacing the context name and endpoint.

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/644

## How to test

Start a new workspace and push a new commit that creates a VM.

## Release Notes

```release-note
```

## Documentation

2022-01-28 12:32 UTC, roboquat commented
@wulfthimm: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-01-28 12:32 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

Associated issue: *#644*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["akosyakov"]} -->

2022-01-28 13:16 UTC, ArthurSens commented
> The script reuses a lot of parts from other scripts and we might refactor it to reduce code.

What do you think of doing that in this PR? 🙂 

Let's refactor early instead of letting it get out of control 😅

2022-01-28 13:45 UTC, wulfthimm commented
> > The script reuses a lot of parts from other scripts and we might refactor it to reduce code.
> 
> What do you think of doing that in this PR? slightly_smiling_face
> 
> Let's refactor early instead of letting it get out of control sweat_smile

That is true but out of the scopre of the issue.

2022-01-28 14:05 UTC, ArthurSens commented
I believe any method that is duplicated can live in an "utils" or "lib" shell, then you can use `source <script>.sh` to import those methods, right?

2022-01-28 15:01 UTC, mads-hartmann requested changes
I agree that we'll soon want a lib folder with files containing common functions that we can `source`, but I don't think quite yet. There is a lot of duplication that can be removed tough and I have suggested ways of doing it in the review :)

2022-01-28 19:50 UTC, wulfthimm commented on dev/preview/install-k3s-kubeconfig.sh
> +ssh "$USER"@127.0.0.1 \
I would rather have self-consistent scripts but sure.

2022-01-28 19:51 UTC, wulfthimm commented on dev/preview/install-k3s-kubeconfig.sh
> +if ! has-harvester-access; then
In case that this does not work during boot or someone is working on an other system I would like to keep those checks.

2022-02-01 09:47 UTC, mads-hartmann approved these changes
Works like a charm.

2022-02-01 09:47 UTC, mads-hartmann commented on dev/preview/install-k3s-kubeconfig.sh
> +if ! has-harvester-access; then
This is access to the Harvester Kubernetes "cluster" so it doesn't care about individual namespaces or VMs that have been created in the cluster - but we can clean up the scripts later so we don't have this check so many places.

2022-02-01 09:47 UTC, roboquat commented
LGTM label has been added.  <details>Git tree hash: bc38b1d66b91c3ce41c9ef871d2dee7022626e94</details>

2022-02-01 09:47 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7893#pullrequestreview-868882800" title="Approved">mads-hartmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

Associated issue: *#644*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["akosyakov"]} -->

2022-02-01 10:09 UTC, wulfthimm commented on dev/preview/install-k3s-kubeconfig.sh
> +if ! has-harvester-access; then
You are right, of course. My reply was wrong.

2022-02-01 10:11 UTC, roboquat commented
New changes are detected. LGTM label has been removed.

2022-02-01 10:48 UTC, mads-hartmann approved these changes
Thanks 🚀

2022-02-01 10:48 UTC, roboquat commented
LGTM label has been added.  <details>Git tree hash: 63cd08f60734d23c1300beffe68acddcad60026f</details>

2022-02-01 10:48 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7893#pullrequestreview-868952607" title="Approved">mads-hartmann</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **akosyakov** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @akosyakov` in a comment when ready.

Associated issue: *#644*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["akosyakov"]} -->

2022-02-02 09:25 UTC, roboquat commented
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod/pull/7893#pullrequestreview-868952607" title="Approved">mads-hartmann</a>*

Associated issue: *#644*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitpod).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["akosyakov"]} -->

2022-02-02 09:25 UTC, merged