Update GitpodWorkspaceTooManyRegularNotActive severity level
gitpod-io/gitpod pull request #8090
Opened 2022-02-08 12:54 UTC by princerachit

## Description

Update the severity of the alert to critical and change the threshold based on previous alerts generated by `GitpodWorkspaceStuckOnStopping` which is usually alerted right after the `GitpodWorkspaceTooManyRegularNotActive` threshold breach.

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/8051

## How to test

NA

## Release Notes

```release-note
None
```

## Documentation

2022-02-08 18:04 UTC, sagor999 commented
/hold
hold until this https://github.com/gitpod-io/runbooks/pull/322 will get merged first.

2022-02-08 18:05 UTC, sagor999 requested changes

2022-02-09 03:27 UTC, princerachit commented on operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
> +              gitpod_workspace_regular_not_active_percentage > 0.15 AND sum(gitpod_ws_manager_workspace_activity_total) > 100
Given that we are not doing any other filtering for other alerts including `GitpodWorkspaceStuckOnStopping` and previously this alert also did not have such filter, I will prefer to just follow the pattern. I looked at previous stats in grafana and the number seems reasonable.

2022-02-09 03:31 UTC, sagor999 commented on operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
> +              gitpod_workspace_regular_not_active_percentage > 0.15 AND sum(gitpod_ws_manager_workspace_activity_total) > 100
ah, I see. Hm. That might backfire in the future when we have more clusters though. But I guess we cam deal with that we can get there.

2022-02-09 03:32 UTC, sagor999 approved these changes

2022-02-09 19:00 UTC, kylos101 commented
/unhold runbook merged

2022-02-09 19:03 UTC, kylos101 commented
/unhold
runbook merged

2022-02-09 19:04 UTC, merged