werft/build/prepare: Add withVM annotation if present on branch name
gitpod-io/gitpod pull request #8635
Opened 2022-03-07 11:38 UTC by ArthurSens

## Description

Since we can't pass annotations on commits anymore, this is needed to make Harvester load tests possible

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/1444

## How to test

Create a new branch from this PR with one of the substrings present:
* `with-vm`
* `with-Vm`
* `with-VM`
* `withvm`
* `withVm`
* `withVM`

Start a new werft job, it should trigger the creation of a Harvester VM.

Or just run `./dev/preview/test/load-test.sh`

## Release Notes

```release-note
NONE
```

2022-03-07 12:54 UTC, mads-hartmann requested changes
Thanks! I have a few change requests before I can approve ☺️

2022-03-07 12:54 UTC, mads-hartmann commented on .werft/jobs/build/prepare.ts
> +    return branchName.includes("with-vm") ||
Just just stick with `with-vm`. Currently the load-test is the only consumer of this so lets keep it simple ☺️

2022-03-07 12:54 UTC, mads-hartmann commented on dev/preview/test/load-test.sh
> +BRANCH_SUFFIX="withVM"
I'd prefer to stick with using hyphens and use `with-vm`

2022-03-07 12:54 UTC, mads-hartmann commented on dev/preview/test/load-test.sh
> +git commit --allow-empty -m "Prepare load test"
We don't need to create a commit anymore now that we don't need to add the Werft commands ☺️

2022-03-07 12:54 UTC, mads-hartmann commented on .werft/build.ts
> +    config = await prepare(werft, config)
I would very much like to keep the config a const and not mutate the config options anywhere ☺️ It makes it easier to debug the the script if you keep the configuration parsing early and treat it as immutable for the rest of the job. So if possible, please move `lookForBranchNameWithVM` to job-config.ts and invoke the function there instead ☺️

2022-03-07 12:54 UTC, mads-hartmann commented on .werft/jobs/build/prepare.ts
> +        if (lookForBranchNameWithVM(config.repository.branch)) {
When you move this to job-config.ts please also log a line that says that we're overriding the value ☺️

2022-03-07 16:02 UTC, ArthurSens commented
@mads-hartmann I ended up changing the strategy completely.

I've just added another conditional when creating the job config

2022-03-08 11:51 UTC, mads-hartmann reviewed
@ArthurSens The TS changes are much nicer, great job! I still have two unresolved comments though ☺️

2022-03-08 11:51 UTC, mads-hartmann commented on dev/preview/test/load-test.sh
> +BRANCH_SUFFIX="withVM"
especially now that the ts code looks for with-vm :)

2022-03-08 13:37 UTC, ArthurSens commented
Whoops, I guess I was a bit distracted when reading the review and missed a couple of things 😬 

I've addressed all comments, and also added a new flag for the load test script.

`--interval` can be useful here in case 30s is too fast or too slow for different scenarios

2022-03-08 13:38 UTC, ArthurSens commented on dev/preview/test/load-test.sh
> +#   ./dev/preview/test/load-test.sh --base-branch-name test --start 1 --end 5 --interval 30
I've changed the example branch name because of the 20 characters restriction 🤔

2022-03-08 13:39 UTC, mads-hartmann approved these changes
Awesome, LGTM. Added the hold label as CI hasn't completed running yet and don't want to mess with Tide :D

2022-03-08 13:43 UTC, ArthurSens commented on dev/preview/test/load-test.sh
>    --longoptions "start:,end:,base-branch-name:" \
```suggestion
  --longoptions "start:,end:,base-branch-name:,interval:" \
```

2022-03-08 13:45 UTC, ArthurSens commented
Sorry mads, just noticed something was missing 😅

2022-03-08 14:22 UTC, mads-hartmann approved these changes
🎉

2022-03-08 14:32 UTC, merged