.werft/build: Refactor installer steps into dedicated interface
gitpod-io/gitpod pull request #8884
Opened 2022-03-18 15:50 UTC by ArthurSens

## Description

This PR tries to reduce amount of code under `.werft/jobs/build/deploy-to-preview-environments.ts` by moving all code related to installer to a dedicated `Installer` interface.

That way, we can make the deploy phase as simple as:
```typescript
werft.phase(deploy)
const installer = newInstaller()
try {
        installer.init(installerSlices.INSTALLER_INIT)
        installer.addPreviewConfiguration(installerSlices.PREVIEW_CONFIG)
        installer.validateConfiguration(installerSlices.VALIDATE_CONFIG)
        installer.render(installerSlices.INSTALLER_RENDER)
        installer.postProcessing(installerSlices.INSTALLER_POST_PROCESSING)
        installer.install(installerSlices.APPLY_INSTALL_MANIFESTS)
    } catch (err) {
        if (!jobConfig.mainBuild) {
            werft.fail(phases.DEPLOY, err)
        }
        exec('exit 0')
    }
werft.done(deploy)
```

I'm opening it as a draft just to collect early feedback on the approach. @gitpod-io/platform do you agree with the approach here?

## How to test

- [ ] Start a preview on core-dev and make sure workspaces start
- [ ] Start a preview on Harvester and make sure workspaces start

## Release Notes

```release-note
NONE
```

2022-03-18 15:59 UTC, ArthurSens commented
/werft run with-vm=true

2022-03-18 16:06 UTC, ArthurSens commented
Tested on both core-dev and Harvester, so turning it into ready for review 🙂

2022-03-29 11:07 UTC, mads-hartmann requested changes
Awesome Arthur. I think this could be improved further, I have left some comments in the review. I'm happy to talk through this more if that's helpful ☺️

2022-03-29 11:07 UTC, mads-hartmann commented on .werft/jobs/build/installer/installer.ts
> +export interface Installer {
In Typescript you generally only use an interface if you intend there to be multiple implementations of the interface. In this case we only have the one so it is preferred to instead just export a class and make your `newInstaller` function the constructor of the class.

2022-03-29 11:07 UTC, mads-hartmann commented on .werft/jobs/build/installer/installer.ts
> +export interface Analytics {
I'd use `type` here instead of interface. This is describing the shape of some data, so we don't intend to use `extends` or `implements` for this ☺️

2022-03-29 11:07 UTC, mads-hartmann commented on .werft/jobs/build/installer/installer.ts
> +function getDevCustomValues(slice: string, configPath: string): void {
All of these functions could be private function or the class or you could leave them here. I'd prefer making them private functions on the class so you can access `this.werft`

2022-03-29 11:07 UTC, mads-hartmann commented on .werft/jobs/build/installer/installer.ts
> +        const werft = getGlobalWerftInstance()
I would make `werft` a private field on the class that you pass in the constructor. That was you can use `this.werft` everywhere in the class.

2022-03-30 08:01 UTC, mads-hartmann submitted a review, later dismissed
I left a few comments that you can follow up on in a later PR ☺️ I added the hold label in case you needed to do some last testing before merging

2022-03-30 08:08 UTC, ArthurSens commented on .werft/jobs/build/installer/installer.ts
> +    constructor(werft: Werft, configPath: string, version: string, proxySecretName: string, domain: string, previewName: string, imagePullSecretName: string, deploymentNamespace: string, analytics: A
Ah nice, I really wasn't enjoying that method signature 😅 

I'll change that real quick

2022-03-30 08:26 UTC, mads-hartmann approved these changes
Awesome, looks great 🛹

2022-03-30 08:29 UTC, merged