telemetry: Enable more fields along with tracing
gitpod-io/gitpod pull request #8915
Opened 2022-03-21 12:22 UTC by Pothulapati

## Description

## Related Issue(s)

Fixes #

## How to test

## Release Notes

```release-note
```

## Documentation

2022-03-21 12:22 UTC, roboquat commented
@Pothulapati: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-21 12:22 UTC, Pothulapati commented
/werft run with-helm=true with-observability=true

2022-03-21 17:29 UTC, kylos101 commented
/werft run with-helm=true with-observability=true with-clean-slate-deployment=true

2022-03-22 06:10 UTC, Pothulapati commented
/werft run with-helm=true with-observability=true with-clean-slate-deployment=true

2022-03-22 09:40 UTC, geropl commented on components/server/src/installation-admin/installation-admin-controller.ts
>              res.status(200).json(await this.telemetryDataProvider.getTelemetryData());
The pattern here is to wrap the actual code in a `try { code } finally { span.finish(); }` to make sure we do not leak resources.

2022-03-22 09:40 UTC, geropl commented on components/server/src/installation-admin/telemetry-data-provider.ts
> +        span.finish();
same here.

2022-03-22 09:41 UTC, geropl requested changes
THx for the PR!

Could you add the try...finally? Happy to quickly approve afterwards. :+1:

2022-03-22 10:48 UTC, geropl submitted a review, later dismissed
Thanks!

2022-03-23 05:51 UTC, Pothulapati commented
/werft run with-helm=true with-observability=true with-clean-slate-deployment=true

2022-03-23 06:30 UTC, Pothulapati commented
/werft run with-clean-slate-deployment=true

2022-03-28 08:11 UTC, easyCZ submitted a review, later dismissed
LGTM

2022-03-28 14:28 UTC, MrSimonEmms submitted a review, later dismissed

2022-03-28 14:33 UTC, MrSimonEmms approved these changes

2022-03-28 14:33 UTC, Pothulapati commented
/unhold

2022-03-29 11:49 UTC, easyCZ approved these changes

2022-03-29 11:50 UTC, merged